/* This is a generated file: do not edit */

struct SEE_string;
extern const unsigned int SEE_nstringtab;

#define STRi(x) SEE_STR_##x
#define STR(x) STRn(SEE_STR_##x)

#if STATIC_STRINGS
/* Address calculated at link time */
# define STRn(i) (&SEE_static_stringtab[i])
extern struct SEE_string SEE_static_stringtab[];
#else
/* Address calculated at run time */
extern struct SEE_string *SEE_stringtab;
# define STRn(i) (SEE_stringtab + (i))
#endif
#define SEE_STR_bad_argc 0
#define SEE_STR_bad_arg 1
#define SEE_STR_internal_error 2
#define SEE_STR_new_not_an_object 3
#define SEE_STR_not_a_constructor 4
#define SEE_STR_no_such_function 5
#define SEE_STR_not_a_function 6
#define SEE_STR_not_callable 7
#define SEE_STR_instanceof_not_object 8
#define SEE_STR_in_not_object 9
#define SEE_STR_no_hasinstance 10
#define SEE_STR_bad_lvalue 11
#define SEE_STR_regex_syntax_error 12
#define SEE_STR_recursion_limit_reached 13
#define SEE_STR_string_limit_reached 14
#define SEE_STR_error 15
#define SEE_STR_no_string_space 16
#define SEE_STR_bad_utf16_string 17
#define SEE_STR_unknown_file 18
#define SEE_STR_string_input_name 19
#define SEE_STR_eval_input_name 20
#define SEE_STR_duplicate_label 21
#define SEE_STR_previous_definition 22
#define SEE_STR_toobject_undefined 23
#define SEE_STR_toobject_null 24
#define SEE_STR_toobject_bad 25
#define SEE_STR_toboolean_bad 26
#define SEE_STR_tonumber_bad 27
#define SEE_STR_tostring_bad 28
#define SEE_STR_defaultvalue_string_bad 29
#define SEE_STR_defaultvalue_number_bad 30
#define SEE_STR_defaultvalue_no_bad 31
#define SEE_STR_not_array 32
#define SEE_STR_array_badlen 33
#define SEE_STR_not_boolean 34
#define SEE_STR_not_function 35
#define SEE_STR_not_cfunction 36
#define SEE_STR_not_number 37
#define SEE_STR_not_regexp 38
#define SEE_STR_not_string 39
#define SEE_STR_not_date 40
#define SEE_STR_null_thisobj 41
#define SEE_STR_apply_not_array 42
#define SEE_STR_bad_radix 43
#define SEE_STR_regexp_bad_string 44
#define SEE_STR_regexp_bad_flag 45
#define SEE_STR_uri_badhex 46
#define SEE_STR_bad_utf8 47
#define SEE_STR_bad_unicode 48
#define SEE_STR_array_sort_error 49
#define SEE_STR_toLocaleString_notfunc 50
#define SEE_STR_toLocaleString_notstring 51
#define SEE_STR_too_many_args 52
#define SEE_STR_string_not_ascii 53
#define SEE_STR_string_contains_null 54
#define SEE_STR_not_implemented 55
#define SEE_STR_implementation_dependent 56
#define SEE_STR_empty_string 57
#define SEE_STR_zero_digit 58
#define SEE_STR_comma 59
#define SEE_STR_write 60
#define SEE_STR_writeval 61
#define SEE_STR_minus 62
#define SEE_STR_name 63
#define SEE_STR_message 64
#define SEE_STR_Error 65
#define SEE_STR_EvalError 66
#define SEE_STR_RangeError 67
#define SEE_STR_ReferenceError 68
#define SEE_STR_SyntaxError 69
#define SEE_STR_TypeError 70
#define SEE_STR_URIError 71
#define SEE_STR_arguments 72
#define SEE_STR_callee 73
#define SEE_STR_source 74
#define SEE_STR_global 75
#define SEE_STR_ignoreCase 76
#define SEE_STR_multiline 77
#define SEE_STR_lastIndex 78
#define SEE_STR_exec 79
#define SEE_STR_test 80
#define SEE_STR_index 81
#define SEE_STR_input 82
#define SEE_STR_parse 83
#define SEE_STR_UTC 84
#define SEE_STR_toDateString 85
#define SEE_STR_toTimeString 86
#define SEE_STR_toLocaleDateString 87
#define SEE_STR_toLocaleTimeString 88
#define SEE_STR_getTime 89
#define SEE_STR_getFullYear 90
#define SEE_STR_getUTCFullYear 91
#define SEE_STR_getMonth 92
#define SEE_STR_getUTCMonth 93
#define SEE_STR_getDate 94
#define SEE_STR_getUTCDate 95
#define SEE_STR_getDay 96
#define SEE_STR_getUTCDay 97
#define SEE_STR_getHours 98
#define SEE_STR_getUTCHours 99
#define SEE_STR_getMinutes 100
#define SEE_STR_getUTCMinutes 101
#define SEE_STR_getSeconds 102
#define SEE_STR_getUTCSeconds 103
#define SEE_STR_getMilliseconds 104
#define SEE_STR_getUTCMilliseconds 105
#define SEE_STR_getTimezoneOffset 106
#define SEE_STR_setTime 107
#define SEE_STR_setMilliseconds 108
#define SEE_STR_setUTCMilliseconds 109
#define SEE_STR_setSeconds 110
#define SEE_STR_setUTCSeconds 111
#define SEE_STR_setMinutes 112
#define SEE_STR_setUTCMinutes 113
#define SEE_STR_setHours 114
#define SEE_STR_setUTCHours 115
#define SEE_STR_setDate 116
#define SEE_STR_setUTCDate 117
#define SEE_STR_setMonth 118
#define SEE_STR_setUTCMonth 119
#define SEE_STR_setFullYear 120
#define SEE_STR_setUTCFullYear 121
#define SEE_STR_toUTCString 122
#define SEE_STR_Object 123
#define SEE_STR_Function 124
#define SEE_STR_Array 125
#define SEE_STR_String 126
#define SEE_STR_Boolean 127
#define SEE_STR_Number 128
#define SEE_STR_Date 129
#define SEE_STR_RegExp 130
#define SEE_STR_Math 131
#define SEE_STR_Infinity 132
#define SEE_STR_NaN 133
#define SEE_STR_apply 134
#define SEE_STR_call 135
#define SEE_STR_charAt 136
#define SEE_STR_charCodeAt 137
#define SEE_STR_concat 138
#define SEE_STR_constructor 139
#define SEE_STR_decodeURI 140
#define SEE_STR_decodeURIComponent 141
#define SEE_STR_encodeURI 142
#define SEE_STR_encodeURIComponent 143
#define SEE_STR_eval 144
#define SEE_STR_fromCharCode 145
#define SEE_STR_hasOwnProperty 146
#define SEE_STR_indexOf 147
#define SEE_STR_isFinite 148
#define SEE_STR_isNaN 149
#define SEE_STR_isPrototypeOf 150
#define SEE_STR_join 151
#define SEE_STR_lastIndexOf 152
#define SEE_STR_length 153
#define SEE_STR_localeCompare 154
#define SEE_STR_match 155
#define SEE_STR_parseFloat 156
#define SEE_STR_parseInt 157
#define SEE_STR_pop 158
#define SEE_STR_propertyIsEnumerable 159
#define SEE_STR_prototype 160
#define SEE_STR_push 161
#define SEE_STR_replace 162
#define SEE_STR_reverse 163
#define SEE_STR_search 164
#define SEE_STR_shift 165
#define SEE_STR_slice 166
#define SEE_STR_sort 167
#define SEE_STR_splice 168
#define SEE_STR_split 169
#define SEE_STR_substring 170
#define SEE_STR_toLocaleLowerCase 171
#define SEE_STR_toLocaleString 172
#define SEE_STR_toLocaleUpperCase 173
#define SEE_STR_toLowerCase 174
#define SEE_STR_toString 175
#define SEE_STR_toUpperCase 176
#define SEE_STR_undefined 177
#define SEE_STR_unshift 178
#define SEE_STR_valueOf 179
#define SEE_STR_MAX_VALUE 180
#define SEE_STR_MIN_VALUE 181
#define SEE_STR_NEGATIVE_INFINITY 182
#define SEE_STR_POSITIVE_INFINITY 183
#define SEE_STR_toFixed 184
#define SEE_STR_toExponential 185
#define SEE_STR_toPrecision 186
#define SEE_STR_E 187
#define SEE_STR_LN10 188
#define SEE_STR_LN2 189
#define SEE_STR_LOG2E 190
#define SEE_STR_LOG10E 191
#define SEE_STR_PI 192
#define SEE_STR_SQRT1_2 193
#define SEE_STR_SQRT2 194
#define SEE_STR_abs 195
#define SEE_STR_acos 196
#define SEE_STR_asin 197
#define SEE_STR_atan 198
#define SEE_STR_atan2 199
#define SEE_STR_ceil 200
#define SEE_STR_cos 201
#define SEE_STR_exp 202
#define SEE_STR_floor 203
#define SEE_STR_log 204
#define SEE_STR_max 205
#define SEE_STR_min 206
#define SEE_STR_pow 207
#define SEE_STR_random 208
#define SEE_STR_round 209
#define SEE_STR_sin 210
#define SEE_STR_sqrt 211
#define SEE_STR_tan 212
#define SEE_STR_escape 213
#define SEE_STR_unescape 214
#define SEE_STR_substr 215
#define SEE_STR_getYear 216
#define SEE_STR_setYear 217
#define SEE_STR_toGMTString 218
#define SEE_STR_object 219
#define SEE_STR_string 220
#define SEE_STR_number 221
#define SEE_STR_unknown 222
#define SEE_STR_unexpected_eof 223
#define SEE_STR_broken_literal 224
#define SEE_STR_escaped_lit_nl 225
#define SEE_STR_invalid_esc_x 226
#define SEE_STR_invalid_esc_u 227
#define SEE_STR_hex_literal_detritus 228
#define SEE_STR_dec_literal_detritus 229
#define SEE_STR_eof_in_c_comment 230
#define SEE_STR_eof_in_regex 231
#define SEE_STR_broken_regex 232
#define SEE_STR_bad_unicode_ident 233
#define SEE_STR_synchronized 234
#define SEE_STR_eleven_filler 235
#define SEE_STR_implements 236
#define SEE_STR_instanceof 237
#define SEE_STR_transient 238
#define SEE_STR_protected 239
#define SEE_STR_interface 240
#define SEE_STR_volatile 241
#define SEE_STR_debugger 242
#define SEE_STR_function 243
#define SEE_STR_continue 244
#define SEE_STR_abstract 245
#define SEE_STR_private 246
#define SEE_STR_package 247
#define SEE_STR_extends 248
#define SEE_STR_boolean 249
#define SEE_STR_finally 250
#define SEE_STR_default 251
#define SEE_STR_native 252
#define SEE_STR_export 253
#define SEE_STR_typeof 254
#define SEE_STR_switch 255
#define SEE_STR_return 256
#define SEE_STR_throws 257
#define SEE_STR_import 258
#define SEE_STR_static 259
#define SEE_STR_delete 260
#define SEE_STR_public 261
#define SEE_STR_double 262
#define SEE_STR_float 263
#define SEE_STR_super 264
#define SEE_STR_short 265
#define SEE_STR_const 266
#define SEE_STR_class 267
#define SEE_STR_while 268
#define SEE_STR_final 269
#define SEE_STR_throw 270
#define SEE_STR_catch 271
#define SEE_STR_break 272
#define SEE_STR_with 273
#define SEE_STR_long 274
#define SEE_STR_void 275
#define SEE_STR_else 276
#define SEE_STR_goto 277
#define SEE_STR_enum 278
#define SEE_STR_this 279
#define SEE_STR_byte 280
#define SEE_STR_case 281
#define SEE_STR_char 282
#define SEE_STR_new 283
#define SEE_STR_try 284
#define SEE_STR_int 285
#define SEE_STR_for 286
#define SEE_STR_var 287
#define SEE_STR_in 288
#define SEE_STR_do 289
#define SEE_STR_if 290
#define SEE_STR_null 291
#define SEE_STR_true 292
#define SEE_STR_false 293
#define SEE_STR___proto__ 294
#define SEE_STR_cfunction_body1 295
#define SEE_STR_cfunction_body2 296
#define SEE_STR_cfunction_body3 297
#define SEE_STR_1 298
#define SEE_STR_2 299
#define SEE_STR_3 300
#define SEE_STR_4 301
#define SEE_STR_5 302
#define SEE_STR_6 303
#define SEE_STR_7 304
#define SEE_STR_8 305
#define SEE_STR_9 306
#define SEE_STR_dollar_underscore 307
#define SEE_STR_dollar_star 308
#define SEE_STR_dollar_ampersand 309
#define SEE_STR_dollar_plus 310
#define SEE_STR_dollar_backquote 311
#define SEE_STR_dollar_quote 312
#define SEE_STR_dollar_1 313
#define SEE_STR_dollar_2 314
#define SEE_STR_dollar_3 315
#define SEE_STR_dollar_4 316
#define SEE_STR_dollar_5 317
#define SEE_STR_dollar_6 318
#define SEE_STR_dollar_7 319
#define SEE_STR_dollar_8 320
#define SEE_STR_dollar_9 321
#define SEE_STR_lastMatch 322
#define SEE_STR_lastParen 323
#define SEE_STR_leftContext 324
#define SEE_STR_rightContext 325
#define SEE_STR__ns_nop 326
#define SEE_STR_anchor 327
#define SEE_STR_big 328
#define SEE_STR_blink 329
#define SEE_STR_bold 330
#define SEE_STR_fixed 331
#define SEE_STR_fontcolor 332
#define SEE_STR_fontsize 333
#define SEE_STR_italics 334
#define SEE_STR_link 335
#define SEE_STR_small 336
#define SEE_STR_strike 337
#define SEE_STR_sub 338
#define SEE_STR_sup 339
